Lista de 16 elementos, transformar en una matriz de 4x4

In [ ]:
import numpy as np


In [ ]:
lista= np.random.randint(1, 17, 16) # Dame 16 numero al azar del 1 al 17
lista


array([ 5,  5,  4,  8,  8, 13, 12, 13,  2,  1, 12,  9, 13, 13,  2, 12])

In [ ]:
import numpy as np

matriz = np.random.randint(1, 17, 16) # Dame 16 numero al azar del 1 al 17
matriz = np.array(matriz).reshape(4, 4) #Crear una matriz de 4x4.

print(matriz)


[[16 13  5 14]
 [13 10  5  2]
 [ 6 13 15  9]
 [ 3  7  3  3]]


In [ ]:
import numpy as np

matriz = np.random.randint(1, 17, 16)
matriz = np.array(matriz).reshape(4, 4)

(np.linalg.det(matriz)) #Calcula el determinante

print(matriz)

[[ 1 16 14  5]
 [ 4  1 14  1]
 [ 2 14 13 12]
 [ 2 14 14  8]]


Areas, Perimetros de triangulos equilateros

In [36]:
import numpy

class Triangulo:   #Creamos clase triangulo
    def __init__(self, lado):
        self.lado = lado

#Calcula el area del tringulo
class Formula(Triangulo):
    def area(self):
        return (self.lado * 2 * numpy.sqrt(3))/2

    def perimetro(self): #Calcula el perimetro
        return self.lado * 3







