## Matrices

In [4]:
import numpy as np

In [10]:
np.random.seed(1)

np.random.randint(1,21,  size =15)  # Se escoge numeros al azar del 1 al 15

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7])

In [15]:
L = [i for i in np.random.randint(1,21,  size =40) if i%2==0]  # Sobre los numeros que dio se escogen los pares
L.sort()
L

[2, 4, 4, 4, 6, 8, 10, 12, 14, 14, 16, 16, 16, 18, 20, 20, 20, 20, 20, 20, 20]

In [21]:
L.remove(8) #Se remueve el numero 8
L

[2, 6, 10, 12, 14, 14, 16, 16, 16, 18, 20, 20, 20, 20, 20, 20]

In [27]:
L + [4] #Se agrega el numero 4 al final de la lista

[6, 10, 12, 14, 16, 16, 16, 18, 20, 20, 20, 20, 20, 20, 4]

In [29]:
L.pop(4)

16

In [25]:
L_arreglo = np.array(L) #Se hace un arreglo
L_arreglo

array([ 6, 10, 12, 14, 16, 16, 16, 18, 20, 20, 20, 20, 20, 20])

In [34]:
len(L_arreglo)

14

In [38]:
L_arreglo.reshape(7,2)  # Se crean matrices de 7x2



array([[ 6, 10],
       [12, 14],
       [16, 16],
       [16, 18],
       [20, 20],
       [20, 20],
       [20, 20]])

In [49]:
M_Matriz = np.array([2,3,14,19,13,0,2,25,6,]).reshape(3,3)  #Se crean matrices
M_Matriz

array([[ 2,  3, 14],
       [19, 13,  0],
       [ 2, 25,  6]])

In [43]:
A_Matriz = np.array([1,5,7,96,87,45,25,95,78,]).reshape(3,3) #Se crean matrices
A_Matriz

array([[ 1,  5,  7],
       [96, 87, 45],
       [25, 95, 78]])

In [50]:
M_Matriz@A_Matriz       # Multiplicacion de matrices

array([[ 640, 1601, 1241],
       [1267, 1226,  718],
       [2552, 2755, 1607]])